# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: iOs
  pool:
    vmImage: 'macos-latest'
  jobs:
    - job: iOs
      steps:

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: '9ac1e3a1-e687-4aa6-ab2b-0108d21425e2'
          definition: '31'
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          itemPattern: |
            **
            !*.cs
            !*.dll
            !win-x86-dll
            !win-x64-dll
            !Csharp-files
          targetPath: '$(System.DefaultWorkingDirectory)'
        displayName: 'Get build-artifacts'

      - script: |
          # Remove UAP-TargetFrameworks
          grep -e '12.0' -rl . | xargs LC_CTYPE=C sed -i '' 's/12.0/15.2/g'

      - script: |
          ls
          mv storj_uplink_second_wrap/storj_uplink_second_wrap.c uplink-c/storj_uplink_second_wrap.c
          cd uplink-c
          ls
          env \
          GOOS='darwin' \
          CC=cc \
          CXX=c++ \
          CGO_ENABLED=1 \
          GOARCH=arm64 \
          CGO_CFLAGS="-arch arm64 -fpic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=12.0" \
          CGO_LDFLAGS="-arch arm64 -dynamic -fpic -shared -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=12.0" \
          go build -ldflags -w -v -tags ios -o "storj_uplink-arm64.a" -buildmode=c-archive
        displayName: 'Prepare and build target iOs arm64'

      - script: |
          echo 'Running xcrun...'
          xcrun -sdk iphoneos clang -arch arm64 -fpic -shared -Wl,-all_load "uplink-c/storj_uplink-arm64.a" -framework Corefoundation -o "uplink-c/storj_uplink.dylib" --verbose
          echo 'Removing archive...'
          rm "uplink-c/storj_uplink-arm64.a"
          echo 'Running install_name_tool'
          install_name_tool -id "@rpath/storj_uplink.framework/storj_uplink" "uplink-c/storj_uplink.dylib"
        displayName: 'Generate Framework for arm64'

      - script: |
          cd uplink-c
          env \
          GOOS='darwin' \
          CC=cc \
          CXX=c++ \
          CGO_ENABLED=1 \
          GOARCH=amd64 \
          CGO_CFLAGS="-arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk" \
          CGO_LDFLAGS="-arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk" \
          go build -ldflags -w -v -tags ios -o "storj_uplink-simx64.dylib" -buildmode=c-shared
        displayName: 'Prepare and build target iOs simx64'

      - script: |
          lipo -create -output "storj_uplink.dylib" "uplink-c/storj_uplink-simx64.dylib" "uplink-c/storj_uplink.dylib"
          #install_name_tool -id "@rpath/storj_uplink.framework/storj_uplink" "storj_uplink.dylib"
          ls -l
          echo 'File-Info'
          file storj_uplink.dylib
          echo 'lipo info'
          lipo -info storj_uplink.dylib 
          echo 'OTOOL'
          otool -L storj_uplink.dylib
        displayName: 'Create fat library containing all iOs-architectures'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/storj_uplink.dylib'
          artifact: 'apple_ios'
          publishLocation: 'pipeline'
        displayName: 'Publish storj_uplink.dylib'